# Generated by Django 4.0.5 on 2022-08-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_collection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='lahore', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Via JazzCash/EasyPaisa', 'Via JazzCash/EasyPaisa'), ('Online Bank Transfer', 'Online Bank Transfer')], default='Cash On Delivery', max_length=255),
        ),
    ]
